


apiVersion: v1
kind: Service
metadata:
  name: clickhouse
spec:
  selector:
    app: clickhouse
  ports:
    - protocol: TCP
      port: 8123
      targetPort: http-port
      name: http
    - protocol: TCP
      port: 9000
      targetPort: native-port
      name: native


