



apiVersion: v1
kind: Pod
metadata:
  name: test-pod
spec:
  containers:
  - name: busybox
    image: busybox
    command: ['sleep', '3600']
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"


